import {test} from 'node:test';import assert from 'node:assert/strict';
import {filterCatalog,actorWorks,clearCategories} from '../electron/category-pages.mjs';
import {filterRows,validateFilterMap,reconcileFilterMap,filterMapKey} from '../electron/category-filter-model.mjs';
import {configureFetch,configureContext,configureRequestEnricher} from '../electron/apk-rpc.mjs';
const item=(id,title=id,selected=false)=>({selector_item_id:id,show_name:title,is_selected:selected});
const rawRow=(type,ids,extra={})=>({row_name:'全部'+type,type,selection_type:2,items:ids.map(id=>item(id)),...extra});
test('official filters use the POST map contract, keep session and selection on paging, reject mixed cursor and arbitrary IDs',async()=>{
 clearCategories();configureContext({common:{},version:''});configureRequestEnricher(async r=>r);const calls=[];
 const rows=[rawRow('genre',['short_play','comic_series'],{refresh_other_selector_row:true}),rawRow('sort',['online_time','hot_collect']),rawRow('gender',['0','1'])];
 configureFetch(async(address,options)=>{const u=new URL(address),body=JSON.parse(options.body);calls.push({u,body,method:options.method});return new Response(JSON.stringify({code:0,data:{...(body.need_selector_panel?{selector_rows:rows,max_expand_num:2}:{}),video_data:[{video_detail:{series_id:String(123456+body.offset),title:'契约测试剧'}}],next_offset:body.offset+12,has_more:true,session_id:'synthetic-session'}}));});
 const first=await filterCatalog();assert.equal(calls.length,1);assert.equal(calls[0].method,'POST');assert.equal(calls[0].u.pathname,'/reading/distribution/category/landpage/v1');assert.deepEqual(calls[0].body,{need_selector_panel:true,select_items:{},client_req_type:3,offset:0,limit:12});assert.equal(first.rows[0].refreshOthers,true);assert.equal(first.maxExpand,2);
 const selected={genre:['comic_series'],sort:['hot_collect'],gender:['0']},chosen=await filterCatalog({context:first.filterContext,selectItems:selected});assert.deepEqual(chosen.selectedFilters,selected);
 const next=await filterCatalog({context:chosen.filterContext,selectItems:selected},chosen.cursor);assert.equal(next.rows.length,3);assert.equal(next.maxExpand,2);assert.equal(calls.at(-1).body.need_selector_panel,false);assert.equal(calls.at(-1).body.client_req_type,2);assert.equal(calls.at(-1).body.offset,12);assert.equal(calls.at(-1).body.session_id,'synthetic-session');assert.deepEqual(calls.at(-1).body.select_items,selected);
 await assert.rejects(filterCatalog({context:first.filterContext,selectItems:{invented:['x']}}),/无效/);await assert.rejects(filterCatalog({context:first.filterContext,selectItems:{genre:['invented']}}),/无效/);await assert.rejects(filterCatalog({context:first.filterContext,selectItems:{genre:['short_play','comic_series']}}),/数量/);await assert.rejects(filterCatalog({context:first.filterContext,selectItems:{genre:['short_play','short_play']}}),/无效/);await assert.rejects(filterCatalog({context:chosen.filterContext,selectItems:{genre:['short_play']}},chosen.cursor),/游标/);await assert.rejects(filterCatalog({context:first.filterContext},chosen.cursor),/游标/);await assert.rejects(actorWorks('123456',chosen.cursor),/会话/);clearCategories();await assert.rejects(filterCatalog({context:first.filterContext}),/过期/);
});
test('genre response can introduce future rows, replace labels/options, remove obsolete selections and requery actual results',async()=>{
 clearCategories();const calls=[];configureFetch(async(_address,options)=>{const b=JSON.parse(options.body);calls.push(b);const comic=b.select_items.genre?.includes('comic_series');const rows=[rawRow('genre',['short_play','comic_series']),rawRow('theme',comic?['comic_theme']:['old_theme']),...(comic?[rawRow('future_dimension',['future_option'],{row_name:'新维度'})]:[])];return new Response(JSON.stringify({code:0,data:{selector_rows:rows,video_data:[{series_id:'123456',title:'动态规则剧'}],next_offset:12,has_more:false}}));});
 const first=await filterCatalog();const old=await filterCatalog({context:first.filterContext,selectItems:{theme:['old_theme']}});const comic=await filterCatalog({context:old.filterContext,selectItems:{genre:['comic_series'],theme:['old_theme']}});assert.equal(comic.rows.length,3);assert.equal(comic.rows[2].title,'新维度');assert.deepEqual(comic.selectedFilters,{genre:['comic_series']});assert.deepEqual(calls.at(-1).select_items,{genre:['comic_series']});assert.equal(calls.length,4);const future=await filterCatalog({context:comic.filterContext,selectItems:{genre:['comic_series'],future_dimension:['future_option']}});assert.deepEqual(future.selectedFilters,{genre:['comic_series'],future_dimension:['future_option']});
});
test('selection constraints are the APK SelectorSelectionType enum, IDs remain scoped by row, false server flags do not reset requested selections',()=>{
 const rows=filterRows([rawRow('sort',['same','b']),rawRow('future',['same','c'],{selection_type:1,multi_selection_bound:2})]);assert.deepEqual(reconcileFilterMap({sort:['same'],future:['same','c']},rows),{sort:['same'],future:['c','same']});assert.throws(()=>validateFilterMap({sort:['same','b']},rows),/数量/);const required=filterRows([rawRow('required',['a','b'],{selection_type:3,items:[item('a','a',true),item('b')]})]);assert.deepEqual(reconcileFilterMap({},required),{required:['a']});assert.throws(()=>validateFilterMap({},required),/至少/);assert.equal(filterMapKey({z:[],b:['2','1'],a:['x']}),filterMapKey({a:['x'],b:['1','2']}));assert.throws(()=>filterRows([rawRow('same',['x']),rawRow('same',['y'])]),/规则/);
});
