import fs from 'node:fs/promises';import assert from 'node:assert/strict';
export async function runSmoke(window,folder,{mediaStatus=()=>({})}={}){
 await fs.mkdir(folder,{recursive:true});const evaluate=code=>window.webContents.executeJavaScript(code,true),delay=ms=>new Promise(r=>setTimeout(r,ms));
 const out={version:'2.3.3',hidden:true,muted:true,online:true,realLoginVerified:false,realCloudSyncVerified:false,nativeWindowTransitionsVerified:false};
 const shot=async name=>{assert.equal(window.isVisible(),false);await delay(150);await fs.writeFile(folder+'/'+name+'.png',(await window.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG());};
 async function until(code){const t=Date.now();while(Date.now()-t<70000){if(await evaluate(code))return;await delay(100);}await shot('timeout');await fs.writeFile(folder+'/timeout-state.json',JSON.stringify(await evaluate('(async()=>({prefs:(await window.hongguo.preferences()).data,videos:[...document.querySelectorAll("video")].map(v=>({active:v.className,ready:v.readyState,paused:v.paused,time:v.currentTime,width:v.videoWidth,error:v.error?.code})),busy:document.querySelector(".player-overlay")?.dataset.busy}))()'),null,2));await fs.writeFile(folder+'/timeout-dom.txt',await evaluate('document.body.innerText'));throw new Error('Timeout: '+code);}
 const click=s=>evaluate('document.querySelector('+JSON.stringify(s)+').click()'),nav=v=>click('[data-view="'+v+'"]'),playing='document.querySelector(".active-video")?.currentTime>.3&&!document.querySelector(".active-video").paused&&document.querySelector(".player-overlay")?.dataset.busy==="false"';
 const change=(s,value)=>evaluate('(()=>{const el=document.querySelector('+JSON.stringify(s)+');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value").set.call(el,'+JSON.stringify(value)+');el.dispatchEvent(new Event("input",{bubbles:true}));el.dispatchEvent(new Event("change",{bubbles:true}));})()');
 assert.equal(window.webContents.isAudioMuted(),true);await until(playing);assert.equal((await evaluate('window.hongguo.preferences()')).data.previewBeforePlay,true);out.defaultPreview=true;out.homeAutoplay=true;
 await evaluate('document.querySelector(".video-stage").dispatchEvent(new PointerEvent("pointermove",{bubbles:true}))');await click('[aria-label="清晰度"]');await until('!!document.querySelector(".media-menu")');assert.equal(await evaluate('document.querySelectorAll("select").length'),0);await delay(1800);assert.equal(await evaluate('document.querySelector(".video-stage").classList.contains("controls-visible")'),true);await shot('quality-menu');
 await click('[aria-label="播放速度"]');await until('document.querySelector(".select-popover").getAttribute("aria-label")==="播放速度"');assert.equal(await evaluate('document.querySelectorAll(".select-popover").length'),1);await evaluate('document.querySelector(".select-popover [data-value=\\"1.5\\"]").click()');await until('document.querySelector(".active-video").playbackRate===1.5');out.customMenuAndSpeed=true;
 await click('[aria-label="清晰度"]');await until('!!document.querySelector(".select-popover")');await evaluate('document.dispatchEvent(new KeyboardEvent("keydown",{key:"ArrowDown",bubbles:true,cancelable:true}));');await evaluate('document.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",bubbles:true,cancelable:true}));');await until('document.querySelector("[aria-label=清晰度]").dataset.value!=="highest"&&'+playing);out.keyboardQualitySelection=true;
 await click('[aria-label="选集"]');await until('document.querySelector(".drama-overview h2")');assert.equal(await evaluate('document.querySelector(".episode-drawer").innerText.includes("集可看")'),false);await shot('drawer');out.redesignedDrawer=true;await click('.drawer-heading [aria-label="收起选集"]');
 await nav('rankings');await until('document.querySelectorAll(".rank-card").length>=10');const before=mediaStatus();const library=await evaluate('window.hongguo.library()');await click('.rank-card');await until('document.querySelectorAll(".series-preview .episode-grid button").length>3');assert.equal(await evaluate('!!document.querySelector(".player-overlay")'),false);await delay(800);assert.deepEqual(mediaStatus(),before);assert.deepEqual(await evaluate('window.hongguo.library()'),library);await shot('rank-preview-light');out.previewNoPlaybackOrHistory=true;
 await evaluate('window.hongguo.savePreferences({theme:"light"})');await until('document.documentElement.dataset.theme==="light"');await shot('preview-light');
 window.setContentSize(820,600);await delay(300);assert.equal(await evaluate('(()=>{const r=document.querySelector(".series-preview").getBoundingClientRect(),f=document.querySelector(".series-preview footer").getBoundingClientRect();return r.x>=0&&r.y>=0&&r.right<=innerWidth&&r.bottom<=innerHeight&&f.bottom<=innerHeight;})()'),true);await shot('preview-narrow');out.previewResponsiveAndLight=true;window.setContentSize(1240,860);await delay(300);
 await click('[aria-label="查看集数"]');await delay(400);assert.equal(await evaluate('document.querySelector(".detail-scroll").scrollTop>0'),true);out.episodeJump=true;
 await click('.series-preview .episode-grid [aria-label="第 3 集"]');assert.equal(await evaluate('document.querySelector(".series-preview footer>span").textContent'),'已选第 3 集');assert.equal(await evaluate('!!document.querySelector(".player-overlay")'),false);await click('[aria-label="播放选中剧集"]');await until('document.querySelector(".player-overlay")?.dataset.episode==="3"&&'+playing);out.selectedEpisodePlayback=true;await click('[aria-label="返回"]');
 await nav('explore');await until('document.querySelectorAll(".explore-page [data-series]").length>0');await click('.explore-page [data-series]');await until('!!document.querySelector(".series-preview")');await click('[aria-label="关闭剧集详情"]');await delay(800);assert.equal(await evaluate('!!document.querySelector(".series-preview")||!!document.querySelector(".player-overlay")'),false);out.closeIgnoresLateDetail=true;
 await change('#query','万妖国录传');await evaluate('document.querySelector(".search-form").requestSubmit()');await until('document.querySelectorAll(".search-family .card").length>3');await click('.search-family .card');await until('document.querySelectorAll(".series-preview .season-button").length>3');const second=await evaluate('document.querySelectorAll(".series-preview .season-button")[1].dataset.series');await evaluate('document.querySelectorAll(".series-preview .season-button")[1].click()');await until('document.querySelector(".series-preview .drama-overview h2")?.textContent.includes("第二季")&&document.querySelectorAll(".series-preview .episode-grid button").length>6');assert.equal(await evaluate('!!document.querySelector(".player-overlay")'),false);
 await evaluate('window.hongguo.savePreferences({theme:"dark",autoplay:false})');await until('document.documentElement.dataset.theme==="dark"');await shot('series-preview-dark');await click('.series-preview .episode-grid [aria-label="第 6 集"]');await click('[aria-label="播放选中剧集"]');await until('document.querySelector(".player-overlay")?.dataset.series==='+JSON.stringify(second)+'&&document.querySelector(".player-overlay").dataset.episode==="6"&&'+playing);out.previewSeasonSelection=true;out.explicitPlayOverridesDisabledAutoplay=true;
 await change('.progress-slider','12');await until('Number(document.querySelector(".progress-slider").value)>=12&&'+playing);await click('[aria-label="返回"]');await click('.search-family .card[data-series="'+second+'"]');await until('document.querySelector(".series-preview footer>span")?.textContent==="已选第 6 集"');await click('[aria-label="播放选中剧集"]');await until('document.querySelector(".player-overlay")?.dataset.episode==="6"&&Number(document.querySelector(".progress-slider").value)>=12&&'+playing);out.previewPreservesResume=true;await click('[aria-label="返回"]');
 await nav('settings');await click('[aria-label="默认播放布局"]');await until('!!document.querySelector(".select-popover:not(.media-menu)")');await shot('settings-menu-dark');await evaluate('document.dispatchEvent(new KeyboardEvent("keydown",{key:"Escape",bubbles:true,cancelable:true}))');await until('!document.querySelector(".select-popover")');await click('[aria-label="点击剧集先查看详情"]');await until('(async()=>!(await window.hongguo.preferences()).data.previewBeforePlay)()');window.webContents.reload();await until('document.querySelector(".active-video")?.readyState>=2');await nav('settings');assert.equal(await evaluate('document.querySelector("[aria-label=点击剧集先查看详情]").checked'),false);out.settingPersists=true;
 if(!await evaluate('document.querySelector("[aria-label=进入视频自动播放]").checked'))await click('[aria-label="进入视频自动播放"]');await until('document.querySelector("[aria-label=进入视频自动播放]").checked');await nav('rankings');await until('document.querySelectorAll(".rank-card").length>=10');await click('.rank-card');await until(playing);assert.equal(await evaluate('!!document.querySelector(".series-preview")'),false);out.directPlaySetting=true;
 assert.equal(window.isVisible(),false);await fs.writeFile(folder+'/preview-smoke.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out));
}
