import fs from 'node:fs/promises';import assert from 'node:assert/strict';
export async function runSmoke(window,folder,{setPlaybackDelay=()=>{},setFeedDelay=()=>{}}={}){
 await fs.mkdir(folder,{recursive:true});const out={version:'2.3.3',at:new Date().toISOString(),hidden:true,muted:true,online:true,realLoginVerified:false,realCloudSyncVerified:false,nativeWindowTransitionsVerified:false};
 const evaluate=code=>window.webContents.executeJavaScript(code,true),delay=ms=>new Promise(r=>setTimeout(r,ms));
 async function shot(name){assert.equal(window.isVisible(),false);await fs.writeFile(folder+'/'+name+'.png',(await window.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG());}
 async function until(code,ms=70000){const at=Date.now();while(Date.now()-at<ms){if(await evaluate(code))return;await delay(200);}await shot('timeout');await fs.writeFile(folder+'/timeout-dom.txt',await evaluate('document.body.innerText'));throw new Error('Timeout: '+code);}
 const click=selector=>evaluate('document.querySelector('+JSON.stringify(selector)+').click()'),textClick=(selector,text)=>evaluate('[...document.querySelectorAll('+JSON.stringify(selector)+')].find(x=>x.textContent.trim()==='+JSON.stringify(text)+').click()'),nav=view=>click('[data-view="'+view+'"]');
 const playing='document.querySelector(".active-video")?.currentTime>.3&&!document.querySelector(".active-video").paused&&document.querySelector(".player-overlay")?.dataset.busy==="false"';
 await until(playing);out.homePlayback=await evaluate('(()=>{const v=document.querySelector(".active-video");return{frames:v.webkitDecodedFrameCount,audio:v.webkitAudioDecodedByteCount};})()');assert.ok(out.homePlayback.frames>0&&out.homePlayback.audio>0);
 await nav('settings');await until('!!document.querySelector("[aria-label=点击剧集先查看详情]")');if(await evaluate('document.querySelector("[aria-label=点击剧集先查看详情]").checked'))await click('[aria-label="点击剧集先查看详情"]');await until('!document.querySelector("[aria-label=点击剧集先查看详情]").checked');await nav('home');await until(playing);
 await click('.window-toggle');await until('!!document.querySelector(".player-window")');await delay(1900);assert.equal(await evaluate('document.querySelector(".video-stage").classList.contains("controls-hidden")'),true);
 await evaluate('window.__revealedDuringSwitch=false;window.__controlObserver=new MutationObserver(()=>{if(document.querySelector(".video-stage")?.classList.contains("controls-visible"))window.__revealedDuringSwitch=true;});window.__controlObserver.observe(document.querySelector(".video-stage"),{attributes:true,attributeFilter:["class"]});');
 const ep=await evaluate('Number(document.querySelector(".player-overlay").dataset.episode)');setPlaybackDelay(1800);await evaluate('document.querySelector(".video-stage").dispatchEvent(new WheelEvent("wheel",{deltaY:120,bubbles:true,cancelable:true}))');await until('Number(document.querySelector(".player-overlay").dataset.episode)==='+(ep+1)+'&&'+playing);await delay(300);assert.equal(await evaluate('window.__revealedDuringSwitch'),false);out.cleanWindowEpisodeSwitch=true;await shot('clean-window-video');setPlaybackDelay(0);await evaluate('window.__controlObserver.disconnect()');await click('.window-toggle');await until('!document.querySelector(".player-window")');
 await evaluate('window.__beforeRefresh=document.querySelector(".player-overlay");document.querySelector("[data-view=home]").dispatchEvent(new MouseEvent("dblclick",{bubbles:true}));');await until(playing+'&&document.querySelector(".player-overlay")!==window.__beforeRefresh');out.doubleDiscoverRefresh=true;
 await nav('rankings');await until('document.querySelectorAll(".rank-card").length>=10&&!document.querySelector(".rankings-page").getAttribute("aria-busy").includes("true")');out.rankTabs=await evaluate('[...document.querySelectorAll(".rank-filters>.filter-row:first-child button")].map(b=>b.textContent)');assert.deepEqual(out.rankTabs,['全部','真人剧','漫剧','AI剧','演员','系列剧']);assert.ok(await evaluate('document.querySelector(".rank-description").textContent.length>10'));await shot('rankings');
 await textClick('.rank-filters>.filter-row:first-child button','演员');await until('document.querySelectorAll("[data-actor]").length>=10');await click('[data-actor]');await until('document.querySelectorAll(".catalog-dialog [data-series]").length>0');out.actorWorks=await evaluate('document.querySelectorAll(".catalog-dialog [data-series]").length');await shot('actor-works');await click('.catalog-dialog [data-series]');await until(playing);out.actorWorkPlayback=true;await click('[aria-label="返回"]');await until('!document.querySelector(".player-overlay")');
 await textClick('.rank-filters>.filter-row:first-child button','系列剧');await until('document.querySelectorAll(".rank-card").length>=10&&document.querySelector(".rank-filters .filter-row button.selected")?.textContent==="系列剧"');out.albumSubTabs=await evaluate('[...document.querySelectorAll(".rank-filters>.filter-row:nth-child(2) button")].map(x=>x.textContent)');assert.deepEqual(out.albumSubTabs,['推荐榜','新季榜']);await shot('series-rank');
 await textClick('.rank-filters>.filter-row:first-child button','全部');await until('document.querySelectorAll(".rank-card").length>=10');await textClick('.rank-filters>.filter-row:nth-child(2) button','预约榜');await until('document.querySelector(".rank-card small")?.textContent.includes("未上线")');await shot('reservation');await click('.rank-card');await until('document.querySelector(".toast")?.textContent.includes("未上线")');assert.equal(await evaluate('!!document.querySelector(".player-overlay")'),false);out.reservationMarkedAndBlocked=true;

 await nav('explore');await textClick('.explore-shortcuts button','筛选');await until('document.querySelectorAll(".category-browser [data-series]").length>=12&&document.querySelector(".category-browser").getAttribute("aria-busy")==="false"');out.categoryInitial=await evaluate('document.querySelectorAll("[data-filter-row]").length');await shot('filter-initial');
 await click('[data-filter-option=cate_36]');await until('document.querySelector(".category-browser").getAttribute("aria-busy")==="false"&&document.querySelector("[data-filter-option=cate_36]").getAttribute("aria-pressed")==="true"');await click('[data-filter-option=online_time]');await until('document.querySelector(".category-browser").getAttribute("aria-busy")==="false"&&document.querySelector("[data-filter-option=online_time]").getAttribute("aria-pressed")==="true"');out.categoryFilteringAndSort=true;
 out.fullFilterOptions=await evaluate('document.querySelectorAll("[data-filter-option]").length');assert.ok(out.fullFilterOptions>90);await shot('inline-filter-options');await click('.filter-fold');assert.equal(await evaluate('document.querySelectorAll("[data-filter-row]").length'),3);await click('.filter-fold');out.inlineFilterFold=true;
 const count=await evaluate('document.querySelectorAll(".category-browser [data-series]").length');await evaluate('document.querySelector(".content").scrollTop=document.querySelector(".content").scrollHeight');await until('document.querySelectorAll(".category-browser [data-series]").length>'+count);out.categoryAutomaticPaging=true;await shot('filter-results');
 await click('[data-filter-option=comic_series]');await until('document.querySelector(".category-browser").getAttribute("aria-busy")==="false"&&document.querySelectorAll(".category-browser [data-series]").length>=12');out.comicFiltering=true;await shot('comic-results');
 assert.equal(window.isVisible(),false);await fs.writeFile(folder+'/rank-filter-smoke.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out));
}
