import { useEffect, useRef, useState } from 'react';
import type { FormEvent } from 'react';
import type { Account, Page, Library, Preferences, Series, Search, WindowState } from './types';
import { unwrap } from './types';
import Player from './Player';
import SeriesPreview from './SeriesPreview';
import Rankings from './Rankings';
import {CatalogLayoutProvider,CatalogGrid,CatalogViewSwitch} from './CatalogLayout';
import LoadMore from './LoadMore';
import SearchBox from './SearchBox';
import { Icon } from './ui';
import Card from './SeriesCard';
import Explore from './Explore';
import SearchResults from './SearchResults';
import { Settings, AccountSettings, DiagnosticsSettings } from './Panels';
const api=window.hongguo,EMPTY:Library={version:1,favorites:[],history:[]};
const message=(e:unknown)=>e instanceof Error?e.message:'加载失败，请重试';
type View='rankings'|'home'|'explore'|'search'|'favorites'|'history'|'settings';
export default function App() {
  const [home,setHome]=useState<Page>(),[library,setLibrary]=useState(EMPTY),[preferences,setPreferences]=useState<Preferences>(),[account,setAccount]=useState<Account>();
  const [view,setView]=useState<View>('home'),[category,setCategory]=useState('推荐'),[feedIndex,setFeedIndex]=useState(0),[input,setInput]=useState(''),[results,setResults]=useState<Search>();
  const [loading,setLoading]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<Series&{initialEpisode?:number;playRequested?:boolean}>(),[toast,setToast]=useState('');
  const [preview,setPreview]=useState<Series>();const openSequence=useRef(0);
  const [windowState,setWindowState]=useState<WindowState>({mode:'normal',fullscreen:false,maximized:false});
  const [searchBusy,setSearchBusy]=useState(false),[searchError,setSearchError]=useState(''),[searchStalls,setSearchStalls]=useState(0),[browseDirection,setBrowseDirection]=useState(1);
  const searchPaging=useRef<number|undefined>(undefined),resultsRef=useRef(results);resultsRef.current=results;
  const paging=useRef<string|undefined>(undefined),homeRef=useRef(home),feedRef=useRef(feedIndex);homeRef.current=home;feedRef.current=feedIndex;
  const request=useRef(0),toastTimer=useRef<ReturnType<typeof setTimeout>>(undefined);
  function notify(text:string){setToast(text);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),4500);}
  const feedCache=useRef(new Map<string,{page:Page;index:number}>()),feedRequests=useRef(new Map<string,Promise<Page>>()),homeSequence=useRef(0),categoryRef=useRef(category);categoryRef.current=category;
  const favoriteQueue=useRef(Promise.resolve());
  function toggleFavorite(item:Series){favoriteQueue.current=favoriteQueue.current.then(async()=>{try{const data=await unwrap(api.favorite(item));setLibrary(data);notify(data.favorites.some(x=>x.id===item.id)?'已添加到追剧':'已取消追剧');}catch(e){notify(message(e));}});}
  function fetchFeed(tab:string){const old=feedRequests.current.get(tab);if(old)return old;const call=unwrap(api.feed(tab)).then(page=>{if(feedRequests.current.get(tab)===call&&!feedCache.current.has(tab))feedCache.current.set(tab,{page,index:0});return page;}).finally(()=>{if(feedRequests.current.get(tab)===call)feedRequests.current.delete(tab);});feedRequests.current.set(tab,call);return call;}
  const [feedRevision,setFeedRevision]=useState(0);
  async function loadHome(tab=categoryRef.current,force=false){if(force){feedCache.current.delete(tab);feedRequests.current.delete(tab);paging.current=undefined;setFeedRevision(n=>n+1);}const token=++homeSequence.current;openSequence.current++;setPreview(undefined);setSelected(undefined);setError('');const cached=feedCache.current.get(tab);setHome(cached?.page);setFeedIndex(cached?.index||0);setLoading(!cached);if(cached)return;try{const data=await fetchFeed(tab);if(token===homeSequence.current&&tab===categoryRef.current){setHome(data);setFeedIndex(0);}}catch(e){if(token===homeSequence.current){setError(message(e));notify(message(e));}}finally{if(token===homeSequence.current)setLoading(false);}}
  function switchCategory(tab:string){if(tab===categoryRef.current)return;if(homeRef.current)feedCache.current.set(categoryRef.current,{page:homeRef.current,index:feedRef.current});categoryRef.current=tab;setCategory(tab);paging.current=undefined;void loadHome(tab);}
  useEffect(()=>{if(home&&preferences)for(const tab of ['推荐','真人剧','漫剧'])if(tab!==categoryRef.current&&!feedCache.current.has(tab))void fetchFeed(tab).catch(()=>{});},[!!home,!!preferences]);
  useEffect(()=>{void loadHome();void unwrap(api.library()).then(setLibrary).catch(e=>notify(message(e)));void unwrap(api.preferences()).then(setPreferences).catch(e=>notify(message(e)));void unwrap(api.account()).then(setAccount);const off=api.onPreferences(setPreferences),offSync=api.onSync(result=>{if(result.ok){setAccount(result.data.account);setLibrary(result.data.library);}else void unwrap(api.account()).then(setAccount);});return()=>{clearTimeout(toastTimer.current);off();offSync();};},[]);
  useEffect(()=>{if(preferences){document.documentElement.dataset.theme=preferences.resolvedTheme;document.documentElement.style.colorScheme=preferences.resolvedTheme;}},[preferences]);
  async function saveSettings(value:Partial<Preferences>){try{setPreferences(await unwrap(api.savePreferences(value)));}catch(e){notify(message(e));}}
  async function doSearch(event?:FormEvent,query=input){event?.preventDefault();if(!query.trim())return;++homeSequence.current;const token=++request.current;searchPaging.current=undefined;setSearchBusy(false);setSearchError('');setSearchStalls(0);openSequence.current++;setPreview(undefined);setSelected(undefined);setView('search');setLoading(true);setError('');setResults(old=>old?.query===query.trim()?old:undefined);try{const data=await unwrap(api.search(query));if(token===request.current)setResults(data);}catch(e){if(token===request.current)setError(message(e));}finally{if(token===request.current)setLoading(false);}}
  async function moreSearch(){const old=resultsRef.current;if(searchPaging.current!==undefined||!old?.hasMore)return;const token=request.current;searchPaging.current=token;setSearchBusy(true);setSearchError('');try{const data=await unwrap(api.search(old.query,old.cursor));if(token!==request.current)return;const ids=new Set(old.items.map(x=>x.id)),added=data.items.filter(x=>!ids.has(x.id));setResults({...data,items:[...old.items,...added]});setSearchStalls(n=>added.length?0:n+1);}catch(e){if(token===request.current)setSearchError(message(e));}finally{if(searchPaging.current===token)searchPaging.current=undefined;if(token===request.current)setSearchBusy(false);}}
  function playSeries(item:Series,episode?:number,requested=false){const token=++openSequence.current;const accept=(s:Series)=>{if(token!==openSequence.current)return;setPreview(undefined);setSelected({...s,initialEpisode:episode,playRequested:requested});};if(item.availability==='unavailable'){notify('这部剧暂不可播放');return;}if(item.availability==='upcoming'){void unwrap(api.detail(item.id)).then(detail=>{if(token!==openSequence.current)return;if(detail.episodeList.length&&detail.episodes>0&&!detail.availability&&detail.contentType!==1002)accept(detail);else notify('这部剧尚未上线，暂不可播放');}).catch(()=>{if(token===openSequence.current)notify('这部剧尚未上线，暂不可播放');});return;}accept(item.openId?{...item,id:item.openId}:item);}
  function openSeries(item:Series){if(preferences?.previewBeforePlay){openSequence.current++;setPreview(item.openId?{...item,id:item.openId}:item);}else playSeries(item);}
  function navigate(next:View){++homeSequence.current;openSequence.current++;setPreview(undefined);setSelected(undefined);++request.current;searchPaging.current=undefined;setSearchBusy(false);setView(next);setError('');setLoading(false);if(next==='home'&&!home)void loadHome();}
  async function moreFeed(advance=false){const old=homeRef.current,tab=categoryRef.current;if(paging.current===tab||!old?.hasMore)return;paging.current=tab;const token=homeSequence.current;try{const data=await unwrap(api.feed(tab,old.cursor));if(token!==homeSequence.current||tab!==categoryRef.current)return;const items=[...old.items,...data.items.filter(x=>!old.items.some(y=>y.id===x.id))],page={...data,items};setHome(page);feedCache.current.set(tab,{page,index:feedRef.current});if(advance&&items.length>feedRef.current+1)setFeedIndex(i=>i+1);else if(advance)notify('暂时没有更多推荐，请稍后再试');}catch(e){if(token===homeSequence.current)notify(message(e));}finally{if(paging.current===tab)paging.current=undefined;}}
  function browse(direction:number){setBrowseDirection(direction);if(direction<0){setFeedIndex(i=>Math.max(0,i-1));return;}if(homeRef.current&&feedRef.current+1<homeRef.current.items.length)setFeedIndex(i=>i+1);else void moreFeed(true);}
  useEffect(()=>{if(home&&feedIndex>=home.items.length-3&&home.hasMore)void moreFeed();},[feedIndex,home?.cursor]);
  useEffect(()=>{const off=api.onWindow(setWindowState);void unwrap(api.windowControl('state')).then(setWindowState);return off;},[]);
  const current=home?.items[feedIndex],collection=view==='favorites'?library.favorites:library.history;
  const immersive=windowState.fullscreen||windowState.mode==='window';
  return <CatalogLayoutProvider defaultLayout={preferences?.defaultCatalogLayout}><div className={"desktop-shell "+(immersive?"immersive-shell":"")}><div className="window-actions"><button aria-label="最小化" onClick={()=>void api.windowControl("minimize")}><span>−</span></button><button aria-label={windowState.maximized?"还原窗口":"最大化"} onClick={()=>void api.windowControl("maximize")}><Icon name="window" size={14}/></button><button aria-label="关闭窗口" onClick={()=>void api.windowControl("close")}><Icon name="close" size={16}/></button></div><aside className="rail"><button className="brand" onClick={()=>navigate('home')}><img src="./app.svg" alt=""/><span>红果<small>好剧，随时看</small></span></button><nav aria-label="主导航">{([['home','home','发现'],['rankings','rank','排行榜'],['explore','explore','探索'],['favorites','heart','追剧'],['history','history','记录']] as const).map(([key,icon,label])=><button className={`nav-button ${(view===key||(key==='explore'&&view==='search'))?'active':''}`} key={key} onClick={()=>navigate(key)} onDoubleClick={key==='home'?()=>{setView('home');void loadHome(categoryRef.current,true);}:undefined} data-view={key}><Icon name={icon}/><span>{label}</span></button>)}</nav><div className="rail-bottom"><button className={`nav-button ${view==='settings'?'active':''}`} data-view="settings" onClick={()=>navigate('settings')}><Icon name="settings"/><span>设置</span></button><small className="version-label">{api.platform==='darwin'?'macOS':'Windows'} · 2.3.4</small></div></aside>
  <main className="main"><header className="toolbar"><div>{view==='home'?<div className="category-tabs">{['推荐','真人剧','漫剧'].map(tab=><button key={tab} className={tab===category?'selected':''} aria-pressed={tab===category} onClick={()=>switchCategory(tab)}>{tab}</button>)}</div>:<h1>{({rankings:'排行榜',explore:'探索',search:'搜索短剧',favorites:'我的追剧',history:'观看记录',settings:'设置',account:'我的账号'} as Record<string,string>)[view]}</h1>}</div><div className="window-drag-region" aria-hidden="true"/><SearchBox value={input} onChange={setInput} onSearch={query=>void doSearch(undefined,query)}/></header>
  {view==='home'?<section className="home-content" data-category={category} aria-busy={loading}>{current&&preferences&&!selected?<div className="feed-frame"><Player key={category+feedRevision} series={current} browseDirection={browseDirection} nextSeries={home?.items[feedIndex+1]} library={library} preferences={preferences} presentation="feed" onLibrary={setLibrary} onClose={()=>{}} onBrowse={browse} notify={notify}/></div>:!selected&&!loading&&error?<div className="empty-state"><p className="feed-error" role="alert">{error}</p><button className="primary" onClick={()=>void loadHome()}>重新加载</button></div>:null}</section>:<div className="content">
  {view==='rankings'?<Rankings library={library} onOpen={openSeries} onFavorite={toggleFavorite}/>:null}
  {view==='explore'?<Explore library={library} onOpen={openSeries} onFavorite={toggleFavorite} onSearch={query=>{setInput(query);void doSearch(undefined,query);}} onRankings={()=>navigate('rankings')}/>:null}
  {view==='search'?results?<><div className="section-heading"><p className="result-count">“{results.query}” · 已找到 {results.items.length} 个结果</p><CatalogViewSwitch/></div><SearchResults key={results.query} items={results.items} query={results.query} library={library} onOpen={openSeries} onFavorite={toggleFavorite}/>{!results.items.length&&<div className="empty-state">没有找到相关剧集</div>}<LoadMore hasMore={results.hasMore} busy={searchBusy} error={searchError} automatic={searchStalls<2&&!selected} className="search-more" onMore={()=>void moreSearch()}/></>:!loading&&!error?<div className="empty-state search-welcome"><Icon name="search" size={38}/><h2>找一部想看的剧</h2><p>输入剧名或关键词，发现你的下一部好剧。</p></div>:null:null}
  {['favorites','history'].includes(view)?<><div className="section-heading"><p>{collection.length} 部短剧</p><CatalogViewSwitch/>{view==='history'&&collection.length>0&&<button className="text-button" onClick={()=>void unwrap(api.clearHistory()).then(setLibrary).catch(e=>notify(message(e)))}>清空本地记录</button>}</div><CatalogGrid>{collection.map(item=><Card key={item.id} item={item} onOpen={openSeries} progress={view==='history'?library.history.find(v=>v.id===item.id):undefined}/>)}</CatalogGrid>{!collection.length&&<div className="empty-state"><Icon name={view==='favorites'?'heart':'history'} size={38}/><h2>{view==='favorites'?'收藏下一部好剧':'从一部好剧开始'}</h2><p>{view==='favorites'?'点亮追剧，喜欢的剧就在这里。':'观看后自动记住集数与进度。'}</p></div>}</>:null}
  {view==='settings'&&preferences?<Settings value={preferences} onChange={v=>void saveSettings(v)}><DiagnosticsSettings/><AccountSettings value={account} onChange={setAccount} onLibrary={setLibrary} notify={notify}/></Settings>:null}
  {loading&&view==='search'&&!results?<div className="search-skeleton" role="status" aria-label="正在搜索"><div className="search-skeleton-heading"/><div className="card-grid">{Array.from({length:6},(_,i)=><div className="search-skeleton-card" key={i}><div/><span/><span/></div>)}</div></div>:loading&&<div className="loading-state" role="status"><div className="spinner"/>正在加载…</div>}{error&&<div className="error-state" role="alert"><p>{error}</p><button className="primary" onClick={()=>void doSearch()}>重试</button></div>}</div>}
  </main>{selected&&preferences&&<Player key={selected.id} series={selected} initialEpisode={selected.initialEpisode} playRequested={selected.playRequested} library={library} preferences={preferences} onLibrary={setLibrary} onClose={()=>setSelected(undefined)} notify={notify}/>}{preview&&<SeriesPreview key={preview.id} item={preview} library={library} onClose={()=>{openSequence.current++;setPreview(undefined);}} onPlay={(item,episode)=>playSeries(item,episode,true)} onFavorite={toggleFavorite} notify={notify}/>} {toast&&<div className="toast" role="status">{toast}</div>}</div></CatalogLayoutProvider>;
}
