import {useEffect,useRef,useState} from 'react';
import type {Library,Page,Series} from './types';
import {unwrap} from './types';
import SeriesCard from './SeriesCard';
import LoadMore from './LoadMore';
import {Icon} from './ui';
import CategoryFilters from './CategoryFilters';
import {CatalogGrid,CatalogViewSwitch} from './CatalogLayout';
const TABS=[{title:'热搜榜',id:'ranklist_hot_search_sc'},{title:'新剧榜',id:'ranklist_new_rank_sc'},{title:'预约榜',id:'ranklist_subscribe'}];
export default function Explore({library,onOpen,onFavorite,onSearch,onRankings}:{library:Library;onOpen:(s:Series)=>void;onFavorite:(s:Series)=>void;onSearch:(query:string)=>void;onRankings:()=>void}){
 const [filtering,setFiltering]=useState(false);
 const [tab,setTab]=useState(TABS[0].id),[page,setPage]=useState<Page>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[words,setWords]=useState<string[]>([]),[wordOffset,setWordOffset]=useState(0),[stalls,setStalls]=useState(0);
 const sequence=useRef(0),inflight=useRef(false),pageRef=useRef(page);pageRef.current=page;
 async function load(more=false){if(more&&(inflight.current||!pageRef.current?.hasMore))return;const previous=pageRef.current,token=++sequence.current;inflight.current=true;setBusy(true);setError('');try{const data=await unwrap(window.hongguo.rankings({selected_items:'all',sub_selected_items:tab},more?previous?.cursor:''));if(token!==sequence.current)return;const known=new Set(previous?.items.map(x=>x.id)),added=data.items.filter(x=>!known.has(x.id));setPage(more&&previous?{...data,items:[...previous.items,...added]}:data);setStalls(n=>more&&!added.length?n+1:0);if(tab===TABS[0].id&&!more){setWords(data.items.map(x=>x.title));setWordOffset(0);}}catch(e){if(token===sequence.current)setError(e instanceof Error?e.message:'探索暂不可用');}finally{if(token===sequence.current){inflight.current=false;setBusy(false);}}}
 useEffect(()=>{pageRef.current=undefined;setPage(undefined);setStalls(0);void load();return()=>{sequence.current++;inflight.current=false;};},[tab]);
 const favorites=new Set(library.favorites.map(x=>x.id));
 if(filtering)return <CategoryFilters library={library} onOpen={onOpen} onFavorite={onFavorite} onClose={()=>setFiltering(false)}/>;
 return <section className="explore-page"><div className="explore-shortcuts"><button onClick={onRankings}><Icon name="rank"/>排行榜</button><button onClick={()=>setTab(TABS[1].id)}><Icon name="new"/>上新</button><button onClick={()=>setFiltering(true)}><Icon name="filter"/>筛选</button></div><div className="explore-guesses"><div className="section-heading"><h2>猜你想搜</h2><button className="text-button" aria-label="换一批推荐词" disabled={!words.length} onClick={()=>setWordOffset(n=>(n+4)%words.length)}><Icon name="sync" size={15}/>换一批</button></div><div className="guess-words">{words.length?Array.from({length:Math.min(4,words.length)},(_,i)=>words[(wordOffset+i)%words.length]).map(word=><button key={word} onClick={()=>onSearch(word)}>{word}</button>):Array.from({length:4},(_,i)=><span className="guess-placeholder" key={i} aria-hidden="true"/>)}</div></div><div className="explore-heading"><div className="explore-tabs" aria-label="探索榜单">{TABS.map(x=><button key={x.id} aria-pressed={tab===x.id} onClick={()=>setTab(x.id)}>{x.title}</button>)}</div><div className="catalog-heading-actions"><CatalogViewSwitch/><button className="text-button" disabled={busy} onClick={()=>void load()}>刷新</button></div></div><CatalogGrid>{page?.items.map(item=><SeriesCard key={item.id} item={item} followed={favorites.has(item.id)} onOpen={onOpen} onFavorite={onFavorite}/>)}{busy&&!page?.items.length&&Array.from({length:12},(_,i)=><div className="explore-placeholder" key={i} aria-hidden="true"><div/><i/></div>)}</CatalogGrid>{page&&<LoadMore hasMore={page.hasMore} busy={busy} error={error} automatic={stalls<2} className="explore-more" onMore={()=>void load(true)}/>} {!page&&error&&<div className="error-state" role="alert"><p>{error}</p><button className="primary" onClick={()=>void load()}>重试</button></div>}</section>;
}
