import { useEffect, useState } from 'react';
import type {ReactNode} from 'react';
import type { Account, Library, Preferences } from './types';
import { unwrap } from './types';
import { Icon } from './ui';
import SelectMenu from './SelectMenu';
const api=window.hongguo;
export function DiagnosticsSettings(){
 const [busy,setBusy]=useState(false),[result,setResult]=useState(''),[failed,setFailed]=useState(false);
 async function exportLogs(){setBusy(true);setResult('');setFailed(false);try{const value=await unwrap(api.exportLogs());setResult(value.canceled?'已取消导出':'已导出 '+value.filename);}catch(e){setFailed(true);setResult(e instanceof Error?e.message:'日志导出失败，请重试');}finally{setBusy(false);}}
 return <section className="settings-card diagnostic-settings"><h2>诊断与日志</h2><div className="setting-row"><div><h3>导出日志</h3><p>导出最近的播放状态、错误分类和接口耗时，便于排查问题。</p><p>不包含手机号、验证码、账号凭据及播放密钥。</p></div><button className="secondary" aria-label="导出日志" disabled={busy} onClick={()=>void exportLogs()}>{busy?'正在导出…':'导出日志'}</button></div>{result&&<p className={failed?'account-error':'subtle'} role={failed?'alert':'status'}>{result}</p>}</section>;
}
export function AccountSettings(props:{value:Account|undefined;onChange:(v:Account)=>void;onLibrary:(v:Library)=>void;notify:(v:string)=>void}){
 const [open,setOpen]=useState(false);
 return <section className="settings-card account-settings"><div className="settings-account-heading"><div><h2>账号与同步</h2><p>{props.value?.loggedIn?'已登录 · 管理登录与观看记录同步':'管理登录与观看记录同步'}</p></div><button className="secondary" data-view="account" aria-expanded={open} aria-controls="settings-account-panel" onClick={()=>setOpen(!open)}>{open?'收起':'账号管理'}<Icon name="back" size={15}/></button></div>{open&&<div className="settings-account-body" id="settings-account-panel"><AccountPanel {...props}/></div>}</section>;
}
export function Settings({value,onChange,children}: {value:Preferences;onChange:(v:Partial<Preferences>)=>void;children?:ReactNode}) {return <div className="settings-page"><section className="settings-card"><h2>外观</h2><div className="setting-row"><div><h3>主题</h3><p>跟随系统，或选择你喜欢的配色</p></div><div className="segmented">{([['system','跟随系统'],['light','浅色'],['dark','深色']] as const).map(([v,label])=><button key={v} aria-pressed={value.theme===v} onClick={()=>onChange({theme:v})}>{label}</button>)}</div></div></section><section className="settings-card"><h2>浏览</h2><div className="setting-row"><div><h3>默认剧集排列</h3><p>排行榜、探索和搜索等目录启动时使用此排列；页面内可随时切换</p></div><SelectMenu label="默认剧集排列" value={value.defaultCatalogLayout} onChange={v=>onChange({defaultCatalogLayout:v as 'grid'|'list'})} options={[{value:'grid',label:'卡片排列'},{value:'list',label:'一行一部剧'}]}/></div></section><section className="settings-card"><h2>播放</h2>{([['previewBeforePlay','点击剧集先查看详情','先查看简介与选集，再点击播放；关闭后直接进入播放'],['homeAutoplay','首页自动播放','切换推荐后自动开始播放'],['autoplay','进入视频自动播放','打开详情或记录时继续观看'],['autoNext','自动下一集','当前剧集结束后继续下一集']] as const).map(([key,title,description])=><div className="setting-row" key={key}><div><h3>{title}</h3><p>{description}</p></div><input className="switch" type="checkbox" aria-label={title} checked={value[key]} onChange={e=>onChange({[key]:e.target.checked})}/></div>)}<div className="setting-row"><div><h3>默认清晰度</h3><p>默认选择本集最高可用清晰度；指定档位不存在时向下匹配</p></div><SelectMenu label="默认清晰度" value={value.defaultQuality} onChange={v=>onChange({defaultQuality:v})} options={['highest','2160','1440','1080','720','540','480','360'].map(q=>({value:q,label:q==='highest'?'最高可用':q+'P'}))}/></div><div className="setting-row"><div><h3>默认播放倍速</h3><p>每次打开视频使用此速度</p></div><SelectMenu label="默认播放倍速" value={String(value.defaultSpeed)} onChange={v=>onChange({defaultSpeed:Number(v)})} options={[.75,1,1.25,1.5,2].map(v=>({value:String(v),label:v+'×'}))}/></div><div className="setting-row"><div><h3>默认播放布局</h3><p>常规播放保留导航；无边框窗口让视频铺满窗口</p></div><SelectMenu label="默认播放布局" value={value.defaultMode} onChange={v=>onChange({defaultMode:v as 'normal'|'window'})} options={[{value:'normal',label:'常规播放'},{value:'window',label:'无边框窗口播放'}]}/></div><div className="setting-row"><div><h3>默认音量</h3><p>{Math.round(value.volume*100)}%</p></div><input aria-label="默认音量" type="range" min={0} max={1} step={0.05} value={value.volume} onChange={e=>onChange({volume:Number(e.target.value)})}/></div></section>{children}<p className="subtle">设置自动保存，下次启动继续使用。</p></div>;}
export function AccountPanel({value,onChange,onLibrary,notify}: {value:Account|undefined;onChange:(v:Account)=>void;onLibrary:(v:Library)=>void;notify:(v:string)=>void}) {
  const [phone,setPhone]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[clock,setClock]=useState(Date.now());
  useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(timer);},[]);
  async function action(name:'send'|'login'|'logout'|'sync') {
    setBusy(true);setError('');
    try {if(name==='send'){onChange(await unwrap(api.sendCode(phone)));notify('验证码已发送，请查看手机短信');}
      if(name==='login'){onChange(await unwrap(api.login(phone,code)));setCode('');onLibrary(await unwrap(api.library()));notify('已登录，正在同步观看记录');const data=await unwrap(api.sync());onChange(data.account);onLibrary(data.library);}
      if(name==='logout'){onChange(await unwrap(api.logout()));onLibrary(await unwrap(api.library()));notify('已退出登录');}
      if(name==='sync'){const data=await unwrap(api.sync());onChange(data.account);onLibrary(data.library);notify('观看记录已同步');}
    }catch(e){setError(e instanceof Error?e.message:'操作失败，请重试');onChange(await unwrap(api.account()));}finally{setBusy(false);}
  }
  const cooldown=Math.max(0,Math.ceil(((value?.retryAt||0)-clock)/1000));
  return <div className="account-card"><div className="account-avatar"><Icon name="user" size={32}/></div><h2>{value?.loggedIn?value.user?.name:'登录红果'}</h2><p className="subtle">{value?.loggedIn?'跨设备继续看，同步你的观看记录。':'使用原红果账号，登录后同步观看记录。'}</p>{value?.loggedIn?<><div className="sync-status">{value.sync.state==='success'?`最近同步 ${new Date(value.sync.at).toLocaleString()}`:value.sync.state==='syncing'?'正在同步…':value.sync.state==='error'?value.sync.message:'尚未同步'}</div><div className="account-actions"><button className="primary" disabled={busy} onClick={()=>void action('sync')}><Icon name="sync" size={17}/>同步记录</button><button className="secondary" disabled={busy} onClick={()=>void action('logout')}>退出登录</button></div></>:<form onSubmit={e=>{e.preventDefault();void action('login');}}><label htmlFor="phone">手机号</label><div className="phone-field"><span>+86</span><input id="phone" type="tel" inputMode="numeric" autoComplete="tel-national" placeholder="请输入手机号" maxLength={11} value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,''))}/></div><label htmlFor="code">短信验证码</label><div className="code-field"><input id="code" inputMode="numeric" autoComplete="one-time-code" placeholder="请输入验证码" maxLength={8} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/><button type="button" disabled={busy||cooldown>0||!/^1[3-9]\d{9}$/.test(phone)} onClick={()=>void action('send')}>{cooldown?`${cooldown} 秒后重发`:'获取验证码'}</button></div><button className="primary login-submit" disabled={busy||!/^1[3-9]\d{9}$/.test(phone)||!/^\d{4,8}$/.test(code)} type="submit">{busy?'正在处理…':'登录并同步'}</button><p className="login-note">点击获取验证码会向填写的手机号发送短信。账号会话在本机加密保存。</p></form>}{error&&<p className="account-error" role="alert">{error}</p>}</div>;
}
