import {useEffect,useRef,useState} from 'react';
import type {Detail,Library,Series} from './types';
import {unwrap} from './types';
import {Cover,Icon} from './ui';
import DramaDetails from './DramaDetails';
export default function SeriesPreview({item,library,onClose,onPlay,onFavorite,notify}:{item:Series;library:Library;onClose:()=>void;onPlay:(s:Detail,episode?:number)=>void;onFavorite:(s:Series)=>void;notify:(s:string)=>void}){
 const [series,setSeries]=useState(item),[detail,setDetail]=useState<Detail>(),[episode,setEpisode]=useState(1),[explicit,setExplicit]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 const dialog=useRef<HTMLElement>(null),savedLibrary=useRef(library);savedLibrary.current=library;
 useEffect(()=>{let canceled=false;setDetail(undefined);setError('');setExplicit(false);void unwrap(window.hongguo.detail(series.id)).then(data=>{if(canceled)return;setDetail(data);const history=savedLibrary.current.history.find(x=>x.id===data.id);setEpisode(data.episodeList.find(x=>x.number===history?.episode&&!x.locked)?.number||data.episodeList.find(x=>!x.locked)?.number||1);}).catch(e=>{if(!canceled)setError(e instanceof Error?e.message:'详情暂不可用');});return()=>{canceled=true;};},[series.id,retry]);
 useEffect(()=>{const before=document.activeElement as HTMLElement;dialog.current?.querySelector<HTMLButtonElement>('button')?.focus({preventScroll:true});return()=>{if(before?.isConnected)before.focus({preventScroll:true});};},[]);
 const unavailable=detail?.availability||detail?.contentType===1002||!detail?.episodeList.some(x=>!x.locked),upcoming=detail?.availability==='upcoming'||series.availability==='upcoming'&&!detail?.episodeList.length;
 return <div className="preview-overlay" onPointerDown={e=>{if(e.target===e.currentTarget)onClose();}}><section ref={dialog} className="series-preview" role="dialog" aria-modal="true" aria-label="剧集详情" onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();onClose();}if(e.key==='Tab'){const nodes=Array.from(dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input')||[]),first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}><header className="detail-dialog-heading"><div><span>先了解，再开看</span><h2>剧集详情</h2></div><button aria-label="关闭剧集详情" onClick={onClose}><Icon name="close" size={18}/></button></header><div className="detail-scroll">{detail?<DramaDetails key={detail.id} detail={detail} library={library} episode={episode} onEpisode={n=>{if(detail.episodeList.find(x=>x.number===n)?.locked){notify('这一集需要原版授权');return;}setEpisode(n);setExplicit(true);}} onFavorite={()=>onFavorite(detail)} onSeason={s=>{const target=s.openId?{...s,id:s.openId}:s;if(target.id===series.id)return;setDetail(undefined);setSeries(target);}} preview/>:<><div className="drama-overview"><Cover source={series.cover} title={series.title}/><div><h2>{series.title}</h2><p>{series.tags.join(' · ')}</p><span>{series.episodes?`全 ${series.episodes} 集`:'待上线'}</span></div></div>{error?<div className="preview-status" role="alert"><p>{error}</p><button className="secondary" onClick={()=>setRetry(n=>n+1)}>重试</button></div>:<div className="preview-skeleton" aria-label="正在获取剧集详情" role="status"><i/><i/><i/></div>}</>}{detail&&unavailable&&<p className="preview-status">{upcoming?'未上线 · 暂不可播放':detail.contentType===1002?'当前是预告，正剧暂未开放':'这部剧暂不可播放'}</p>}</div><footer><span>{detail&&!unavailable?`已选第 ${episode} 集`:error?'详情获取失败':detail?'暂不可播放':'正在获取选集'}</span>{detail&&!unavailable&&<button className="text-button preview-episode-jump" aria-label="查看集数" onClick={()=>dialog.current?.querySelector(".drama-episodes")?.scrollIntoView({block:"start",behavior:"smooth"})}>选集<Icon name="down" size={12}/></button>}<button className="primary preview-play" aria-label="播放选中剧集" disabled={!detail||!!unavailable} onClick={()=>detail&&onPlay(detail,explicit?episode:undefined)}><Icon name="play" size={16}/>播放{detail&&!unavailable?`第 ${episode} 集`:''}</button></footer></section></div>;
}
